---
- hosts: localhost
  connection: local
  vars_files:
    - aws_keys.yml

  tasks:
  - name: Gather ec2 instances
    ec2_instance_facts:
      region: "{{ region }}"
      filters:
        "tag:type": "prometheus_training"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    register: ec2

  - name: Terminate ec2 instances
    ec2:
      instance_ids: '{{ item.instance_id }}'
      state: absent
      wait: true
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    with_items: "{{ ec2.instances }}"

  - name: Remove security group
    ec2_group:
      name: "prometheus_training"
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      state: absent