---
- hosts: localhost
  connection: local
  vars:
    region: eu-central-1
  vars_files:
    - aws_keys.yml

  tasks:
  - name: Gather ec2 instances
    ec2_instance_facts:
      region: "{{ region }}"
      filters:
        instance-state-name: running
        "tag:type": "prometheus_training"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    register: ec2

  - debug: var=ec2

  - name: Terminate ec2 instances
    ec2:
      instance_ids: '{{ item.instance_id }}'
      state: absent
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    with_items: "{{ ec2.instances }}"